### ISSUE TITLE
[Bug]: 新初始化vitepress 项目 再使用主题 页面无显示 控制面板报错

### ISSUE THREAD

**Issue by zhoupeng260641663** [MaLuns/vitepress-theme-async#10]
### 使用的 vitepress-Theme-Asycn 版本？ | What version of vitepress-Theme-Asycn are you use?

0.0.22

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

<img width="1830" alt="image" src="https://github.com/user-attachments/assets/070a08b6-3fe3-4b71-8a73-1af0f0c0a995">

### 出现问题网站 | Website

本地项目

**Comment by MaLuns** [comment]
可以添加 links 配置,这个应该是添加了友链页,但是没添加友链导致的,后面兼容处理下

**Comment by zhoupeng260641663** [comment]
> 可以添加 links 配置,这个应该是添加了友链页,但是没添加友链导致的,后面兼容处理下

你好，添加links配置解决 不过出现了新的问题 提示 TrmPagePost.vue:72 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'date') (TrmPagePost.vue:72:76)

我尝试添加posts文件夹与子md文件问题依旧

**Comment by MaLuns** [comment]
> > 可以添加 links 配置,这个应该是添加了友链页,但是没添加友链导致的,后面兼容处理下
> 
> 你好，添加links配置解决 不过出现了新的问题 提示 TrmPagePost.vue:72 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'date') (TrmPagePost.vue:72:76)
> 
> 我尝试添加posts文件夹与子md文件问题依旧

Frontmatter 里 加上日期 试试

**Comment by zhoupeng260641663** [comment]
> > > 可以添加 links 配置,这个应该是添加了友链页,但是没添加友链导致的,后面兼容处理下
> > 
> > 
> > 你好，添加links配置解决 不过出现了新的问题 提示 TrmPagePost.vue:72 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'date') (TrmPagePost.vue:72:76)
> > 我尝试添加posts文件夹与子md文件问题依旧
> 
> Frontmatter 里 加上日期 试试

我是复制初始化新博客中的posts文件夹的。
代码内容如下
`---
title: Hello Theme Async
date: 2022-09-21 15:08:29
cover: [https://hexo-theme-async.imalun.com/imgs/demo2.png]
sticky: 1
---

![1663833969157.png](https://hexo-theme-async.imalun.com/imgs/demo2.png)_示例图_

Welcome to [vitepress-theme-async](https://vitepress-theme-async.imalun.com/).



## Hello

:tada::tada::tada::tada::tada::tada:

## Vitepress Theme Async

- docs: [https://vitepress-theme-async.imalun.com/](https://vitepress-theme-async.imalun.com/)
`

**Comment by 57Darling02** [comment]
我也遇到了相同的问题，添加posts中的data并未解决
